### ISSUE TITLE
Loggning av Email, loggar substrängar av email som randomstring

### ISSUE THREAD

**Issue by jhzn** [JoForsberg/Test#14]
När programmet loggar så loggar random email funktionen även rader av randomstrings och skrivs ut.
Detta bör inte hända. Duplicering av information. Det inte går att skilja mellan randomstring och randomstring från email loggen.

Windows 10 , i5 8gb ram, 256 ssd.

Start program
Check Print logs to File
Click generate random email address
Open log file
Observe picture

![image](https://cloud.githubusercontent.com/assets/14824730/18004510/aacb822e-6b94-11e6-8840-05bbe397ae6f.png)

**Comment by JoForsberg** [comment]
Saknar en kort beskrivning av buggen. 
Vad är det du förväntar dig ska hända?

**Comment by jhzn** [comment]
@JoForsberg Fixed

**Comment by marnil-hot** [comment]
Varför är detta ett problem?

**Comment by jhzn** [comment]
@marnil-hot För att det inte går att skilja mellan randomstring och randomstring från email loggen.
