### ISSUE TITLE
Screen goes black

### ISSUE THREAD

**Issue by jhzn** [JoForsberg/Test#22]
Screen goes black while moving the window to the corner while a operation that takes a while to complete, around ~1000000 characters.
![image](https://cloud.githubusercontent.com/assets/14824730/18004962/736672aa-6b97-11e6-8534-6429a212253d.png)

**Comment by marnil-hot** [comment]
What system did you perform this on? Could it be that your computer is too weak?

**Comment by marnil-hot** [comment]
Closed. My screen just freezes and doesn't go black.

**Comment by jhzn** [comment]
@marnil-hot How dare you insult my machine?!!!???
