### ISSUE TITLE
Wrong output in Ascii Table

### ISSUE THREAD

**Issue by AhmedMahadawi** [JoForsberg/Test#25]
When you choose the string length of 0 characters and generate Ascii table the output gives you a wrong value and no error message.
1. Open the crappy little datagenerator
2. Type 0 in the string of lenght input
3. Press the Get Ascii Table button.

You can generate the used on your platform from number 32 to 255. And you get wrong output when you generate string lenght of 0. The output is wrong and no error message accured.

**Comment by marnil-hot** [comment]
Screenshot? What computer did you test on (memory, operating sytem etc)?

**Comment by marnil-hot** [comment]
Closed. Not a bug.
