### ISSUE TITLE
Spelling error on label

### ISSUE THREAD

**Issue by asaow** [JoForsberg/Test#27]
The label Captial Ch... is spelled wrong, it should be Capital Ch... instead.

To reproduce:
1. Start application
2. Look at the left label below the input field.

Bug: Captial 
Expected result: Capital

Additional information:
Java 8 Update 102
MacBook Air, OS X Yosemite, version 10.10.5

**Comment by marnil-hot** [comment]
I'm pretty shure the spelling is correct.

**Comment by asaow** [comment]
![skarmavbild 2016-08-26 kl 14 49 02](https://cloud.githubusercontent.com/assets/15607785/18005828/abcd7f44-6b9c-11e6-9617-901f09228ddb.png)

**Comment by asaow** [comment]
And it's sure, not shure... ;)

**Comment by marnil-hot** [comment]
How rude! Are you disrespecting my authorita in spelling?

**Comment by asaow** [comment]
Yes, I have a Cambridge Certificate of Proficiency in English (CPE) from Harrow College, England

And it's authority...

**Comment by iDuffin** [comment]
![1533902_145744045766932_8252991984672232899_n](https://cloud.githubusercontent.com/assets/15889054/18006669/f05d997e-6ba0-11e6-86cd-309b8e740afd.jpg)

**Comment by marnil-hot** [comment]
![image](https://cloud.githubusercontent.com/assets/17824076/18006677/f9ef8d94-6ba0-11e6-86bd-b8528cb4a1e6.png)

**Comment by iDuffin** [comment]
![27679571fc165248633880d5d2b7b59606e8b85ded42812791f3b962397d8bfb](https://cloud.githubusercontent.com/assets/15889054/18006740/57b11dda-6ba1-11e6-87fd-6b6144b6156d.jpg)
