### ISSUE TITLE
Texten från "Output" rutan raderas inte om man vill generera en sträng med längden 0

### ISSUE THREAD

**Issue by mAdTYzz** [JoForsberg/Test#28]
Texten i "Output" rutan raderas inte om man generar en sträng med valfritt längd innan och sen försöker man generera en sträng med längden 0.

ALLVARLIGHETSGRAD: Lätt

BUGG: Föregående resultatet raderas inte från "Output" rutan.
FÖRVÄNTAT RESULTAT: Att "Output" rutan ska vara tom.

**Comment by marnil-hot** [comment]
Det är en feature, inte en bugg.

**Comment by mAdTYzz** [comment]
Vi använde google translate som orakel och där försvinner översättningen om man raderar ursprungliga texten. Dvs. om ursprungliga texten har längden 0. Därför ansåg vi att vår testapplikation borde också göra det. Det kan skapa förvirring för användaren och det kan också vara ett sätt att tömma rutan ifall det önskas.
