### ISSUE TITLE
Loggfilen töms när man startar programmet

### ISSUE THREAD

**Issue by jhzn** [JoForsberg/Test#5]
DataGenerationLog.txt blir nollställd när man startar om programmet.

Filen i samma map som programmet.

Windows 10, i5 8gb ram, 256 ssd.

Starta programmet
Kryssa i Print logs to File
Generera en sträng
Kolla loggfilen
Stäng programmet
Öppna programmet
Kolla loggfilen

**Comment by JoForsberg** [comment]
Lite feedback;
Vart ligger filen?
Vill gärna se steg för att reproducera.

Detta skulle mycket väl kunna vara en feature för att få loggen ny när du startar en ny instans/session av programmet.

**Comment by jhzn** [comment]
@JoForsberg Det kan vara en feature, jag bara meddelare om mjukvarans beteende. :D
